apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-digitalekanaler-modules
  title: terraform-digitalekanaler-modules
  description: Common terraform modules for our backend services
spec:
  type: library
  lifecycle: production
  owner: team-dx
