version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

terraform_versions: &terraform_versions
  - 1.0.8
  - 1.1.4

terraform_folders: &terraform_folders
  - ./microservice-apigw-proxy

workflows:
  validate:
    jobs:
      - terraform/fmt:
          checkout: true
          recursive: true
      - terraform/validate:
          checkout: true
          backend: false
          matrix:
            parameters:
              tag: *terraform_versions
              path: *terraform_folders